name: Update issues
run-name: "Update issues"

on:
  workflow_dispatch:
  issues:
    types: [edited]

jobs:
  update:
    name: Update issues
    if: ${{ contains('variant:', github.event.issue.title) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          numOpenIssues="$(gh api graphql -F owner=$OWNER -F name=$REPO -f query='
            query($name: String!, $owner: String!) {
              repository(owner: $owner, name: $name) {
                issues(states:OPEN){
                  totalCount
                }
              }
            }
          ' --jq '.data.repository.issues.totalCount')"

          echo 'NUM_OPEN_ISSUES='$numOpenIssues >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
      - run: |
          gh issue create --title "Issue report" --body "$NUM_OPEN_ISSUES issues remaining" --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      # - uses: actions/checkout@v4
      #   with:
      #     token: ${{ secrets.PAT }}
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 23
      # - run: npm update probe.rs-data
      # - run: npm run build
      # - name: git commit
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git commit -am "Update issues"
      #     git push
